export interface ComponentCategory {
  slug: string
  name: string
  components: { name: string }[]
  isNew?: boolean
}

export const categories: ComponentCategory[] = [ 
  {
    slug: "accordion",
    name: "Accordion",
    components: [
      { name: "accordion-01" },
      { name: "accordion-02" },
      { name: "accordion-03" },
      { name: "accordion-04" },
      { name: "accordion-05" },
      { name: "accordion-06" }, 
    ],
  },
  {
    slug: "button",
    name: "Button",
    isNew: true,
    components: [
      { name: "button-48" },
      { name: "button-49" },
      { name: "button-50" },
      { name: "button-51" },
      { name: "button-01" },
      { name: "button-02" },
      { name: "button-03" },
      { name: "button-04" },
      { name: "button-05" },
      { name: "button-06" },
      { name: "button-07" },
      { name: "button-08" },
      { name: "button-09" },
      { name: "button-10" },
      { name: "button-11" },
      { name: "button-12" },
      { name: "button-13" },
      { name: "button-14" },
      { name: "button-15" },
      { name: "button-16" },
      { name: "button-17" },
      { name: "button-18" },
      { name: "button-43" },
      { name: "button-19" },
      { name: "button-20" },
      { name: "button-21" },
      { name: "button-22" },
      { name: "button-23" },
      { name: "button-24" },
      { name: "button-25" },
      { name: "button-26" },
      { name: "button-27" },
      { name: "button-28" },
      { name: "button-29" },
      { name: "button-30" },
      { name: "button-31" },
      { name: "button-32" },
      { name: "button-33" },
      { name: "button-46" },
      { name: "button-34" },
      { name: "button-35" },
      { name: "button-36" },
      { name: "button-37" },
      { name: "button-38" },
      { name: "button-39" },
      { name: "button-40" },
      { name: "button-41" },
      { name: "button-42" },
      { name: "button-44" },
      { name: "button-47" },
      { name: "button-45" },
    ],
  }, 
  {
    slug: "card",
    name: "Card",
    components: [
      { name: "card-01" },
      { name: "card-08" },
      { name: "card-02" },
      { name: "card-09" },
      { name: "card-03" },
      { name: "card-04" },
      { name: "card-06" },
      { name: "card-05" },
      { name: "card-07" },
      { name: "card-10" },
    ],
  },
  {
    slug: "alert",
    name: "Alert",
    components: [
      { name: "alert-01" },
      { name: "alert-02" },
      { name: "alert-03" },
      { name: "alert-04" },
      { name: "alert-05" }, 
    ],
  },
  {
    slug: "alert-dialog",
    name: "Alert Dialog",
    components: [
      { name: "alert-dialog-01" },
      { name: "alert-dialog-02" },
      { name: "alert-dialog-03" },
      { name: "alert-dialog-04" },
      { name: "alert-dialog-05" }, 
    ],
  },
  {
    slug: "avatar",
    name: "Avatar",
    components: [
      { name: "avatar-01" },
      { name: "avatar-02" },
      { name: "avatar-03" },
      { name: "avatar-04" },
      { name: "avatar-05" },
      { name: "avatar-06" }, 
    ],
  },
  {
    slug: "badge",
    name: "Badge",
    components: [
      { name: "badge-01" },
      { name: "badge-02" },
      { name: "badge-03" },
      { name: "badge-04" },
      { name: "badge-05" },
      { name: "badge-06" }, 
    ],
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    components: [
      { name: "breadcrumb-01" },
      { name: "breadcrumb-02" },
      { name: "breadcrumb-03" },
      { name: "breadcrumb-04" },
      { name: "breadcrumb-05" },
      { name: "breadcrumb-06" }, 
    ],
  },
  {
    slug: "pagination",
    name: "Pagination",
    components: [
      { name: "pagination-01" },
      { name: "pagination-02" },
      { name: "pagination-03" },
      { name: "pagination-04" },
      { name: "pagination-05" },
      { name: "pagination-06" }, 
    ],
  },
]

export function getCategory(slug: string): ComponentCategory | undefined {
  return categories.find((category) => category.slug === slug)
}
