export interface ComponentCategory {
  slug: string
  name: string
  components: { name: string }[]
  isNew?: boolean
}

export const categories: ComponentCategory[] = [
  {
    slug: "accordion",
    name: "Accordion",
    components: [
      { name: "accordion-01" },
      { name: "accordion-02" },
      { name: "accordion-03" },
      { name: "accordion-04" },
      { name: "accordion-05" },
      { name: "accordion-06" },
      { name: "accordion-07" },
    ],
  },
  {
    slug: "button",
    name: "Button", 
    components: [
      { name: "button-48" },
      { name: "button-49" },
      { name: "button-50" },
      { name: "button-51" },
      { name: "button-52" },
      { name: "button-53" },
      { name: "button-54" },
      { name: "button-01" },
      { name: "button-02" },
      { name: "button-03" },
      { name: "button-04" },
      { name: "button-05" },
      { name: "button-06" },
      { name: "button-07" },
      { name: "button-08" },
      { name: "button-09" },
      { name: "button-10" },
      { name: "button-11" },
      { name: "button-12" },
      { name: "button-13" },
      { name: "button-14" },
      { name: "button-15" },
      { name: "button-16" },
      { name: "button-17" },
      { name: "button-18" },
      { name: "button-43" },
      { name: "button-19" },
      { name: "button-20" },
      { name: "button-21" },
      { name: "button-22" },
      { name: "button-23" },
      { name: "button-24" },
      { name: "button-25" },
      { name: "button-26" },
      { name: "button-27" },
      { name: "button-28" },
      { name: "button-29" },
      { name: "button-30" },
      { name: "button-31" },
      { name: "button-32" },
      { name: "button-33" },
      { name: "button-46" },
      { name: "button-34" },
      { name: "button-35" },
      { name: "button-36" },
      { name: "button-37" },
      { name: "button-38" },
      { name: "button-39" },
      { name: "button-40" },
      { name: "button-41" },
      { name: "button-42" },
      { name: "button-44" },
      { name: "button-47" },
      { name: "button-45" },
    ],
  },
  {
    slug: "card",
    name: "Card", 
    components: [
      { name: "card-01" },
      { name: "card-08" },
      { name: "card-02" },
      { name: "card-09" },
      { name: "card-03" },
      { name: "card-04" },
      { name: "card-06" },
      { name: "card-05" },
      { name: "card-07" },
      { name: "card-10" },
    ],
  },
  {
    slug: "chart",
    name: "Chart", 
    components: [
      { name: "chart-01" }, 
      { name: "chart-02" }, 
      { name: "chart-03" }, 
    ],
  },
  {
    slug: "alert",
    name: "Alert",
    components: [
      { name: "alert-01" },
      { name: "alert-02" },
      { name: "alert-03" },
      { name: "alert-04" },
      { name: "alert-05" },
    ],
  },
  {
    slug: "alert-dialog",
    name: "Alert Dialog",
    components: [
      { name: "alert-dialog-01" },
      { name: "alert-dialog-02" },
      { name: "alert-dialog-03" },
      { name: "alert-dialog-04" },
      { name: "alert-dialog-05" },
    ],
  },
  {
    slug: "avatar",
    name: "Avatar",
    components: [
      { name: "avatar-01" },
      { name: "avatar-02" },
      { name: "avatar-03" },
      { name: "avatar-04" },
      { name: "avatar-05" },
      { name: "avatar-06" },
    ],
  },
  {
    slug: "award",
    name: "Award",
    isNew: true,
    components: [
      { name: "award-01" },
      { name: "award-02" },
      { name: "award-03" },
      { name: "award-04" },
      { name: "award-05" },
      { name: "award-06" },
    ],
  },
  {
    slug: "badge",
    name: "Badge",
    components: [
      { name: "badge-01" },
      { name: "badge-02" },
      { name: "badge-03" },
      { name: "badge-04" },
      { name: "badge-05" },
      { name: "badge-06" },
    ],
  },
  {
    slug: "book",
    name: "Book",
    isNew: true,
    components: [
      { name: "book-01" },
      { name: "book-02" },
      { name: "book-03" },
      { name: "book-04" },
      { name: "book-05" },
      { name: "book-06" },
    ],
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    components: [
      { name: "breadcrumb-01" },
      { name: "breadcrumb-02" },
      { name: "breadcrumb-03" },
      { name: "breadcrumb-04" },
      { name: "breadcrumb-05" },
      { name: "breadcrumb-06" },
    ],
  },
  {
    slug: "device",
    name: "Device", 
    components: [
      { name: "device-01" },
      { name: "device-02" },
      { name: "device-03" },
      { name: "device-04" },
    ],
  },
  {
    slug: "gauge",
    name: "Gauge",
    isNew: true,
    components: [
      { name: "gauge-01" },
      { name: "gauge-02" },
      { name: "gauge-03" },
      { name: "gauge-04" },
      { name: "gauge-05" },
      { name: "gauge-06" },
      { name: "gauge-07" },
      { name: "gauge-08" },
      { name: "gauge-09" },
    ],
  },
  {
    slug: "text",
    name: "Text",
    isNew: true,
    components: [
      { name: "text-01" },
      { name: "text-02" },
      { name: "text-03" },
      { name: "text-04" },
      { name: "text-05" },
      { name: "text-06" },
      { name: "text-07" },
      { name: "text-08" },
      { name: "text-09" },
      { name: "text-10" },
      { name: "text-11" },
      { name: "text-12" },
      { name: "text-13" },
      { name: "text-14" },
      { name: "text-15" },
      { name: "text-16" },
    ],
  },
  {
    slug: "spinner",
    name: "Spinner", 
    components: [
      { name: "spinner-01" },
      { name: "spinner-02" },
      { name: "spinner-03" },
      { name: "spinner-04" },
      { name: "spinner-05" },
      { name: "spinner-06" },
      { name: "spinner-07" },
      { name: "spinner-08" },
      { name: "spinner-09" },
    ],
  },
  {
    slug: "pagination",
    name: "Pagination",
    components: [
      { name: "pagination-01" },
      { name: "pagination-02" },
      { name: "pagination-03" },
      { name: "pagination-04" },
      { name: "pagination-05" },
      { name: "pagination-06" },
    ],
  },
]

export function getCategory(slug: string): ComponentCategory | undefined {
  return categories.find((category) => category.slug === slug)
}
