import { IconMetadata, IconsProps } from "./types";
import type { ComponentType } from "react"

import { 
  ArrowBigDownMetadata, 
  ArrowBigDownDashMetadata, 
  ArrowBigUpDashMetadata, 
  ArrowBigUpMetadata, 
  ArrowBigRightDashMetadata, 
  ArrowBigRightMetadata, 
  ArrowBigLeftDashMetadata, 
  ArrowDownMetadata,
  ArrowDown01Metadata,
  ArrowDown10Metadata,
  ArrowDownAZMetadata,
  AArrowDownMetadata,
  AArrowUpMetadata,
  ALargeSmallMetadata,
  AppWindowMetadata,
  ArrowBigLeftMetadata ,
  AppWindowMacMetadata,
  Axis3dMetadata,
  BetweenHorizontalEndMetadata,
  BetweenHorizontalStartMetadata,
  BetweenVerticalEndMetadata,
  BetweenVerticalStartMetadata,
  BlendMetadata,
  BookTypeMetadata,
  AnvilMetadata,
  BrickWallMetadata,
  BuildingMetadata,
  Building01Metadata,
  CastleMetadata,
  ChurchMetadata,
  DamMetadata,
  FactoryMetadata,
  FenceMetadata,
  HospitalMetadata,
  HotelMetadata,
  HouseMetadata,
  AlignCenterHorizontalMetadata,
  AlignCenterVerticalMetadata,
  AlignEndHorizontalMetadata,
  AlignEndVerticalMetadata,
  AlignHorizontalDistributeCenterMetadata,
  AlignHorizontalDistributeEndMetadata,
  AlignHorizontalDistributeStartMetadata,
  AlignHorizontalJustifyCenterMetadata,
  AlignHorizontalJustifyEndMetadata,
  AlignHorizontalJustifyStartMetadata,
  AlignHorizontalSpaceAroundMetadata,
  AlignHorizontalSpaceBetweenMetadata,
  BadgeMetadata,
  BlocksMetadata,
  BoxMetadata,
  BoxesMetadata,
  CircleMetadata,
  CircleDashedMetadata,
  CircleDotMetadata,
  CircleDotDashedMetadata,
  CircleOffMetadata,
  CircleSlash2Metadata,
  CircleSmallMetadata,
  ClubMetadata,
  CirclePlusMetadata,
  GrabMetadata,
  LassoMetadata,
  LassoSelectMetadata,
  LoaderMetadata,
  LoaderCircleMetadata,
  LoaderPinwheelMetadata,
  MousePointerMetadata,
  MousePointer1Metadata,
  MousePointerBanMetadata,
  MousePointerClickMetadata,
  AccessibilityMetadata,
  MoveMetadata,
  BabyMetadata,
  BadgeHelpMetadata,
  CircleHelpMetadata,
  ContrastMetadata,
  EarOffMetadata,
  EarMetadata,
  EclipseMetadata,
  EyeClosedMetadata,
  EyeOffMetadata,
  EyeMetadata,
  GlassesMetadata,
  AsteriskMetadata,
  BadgePercentMetadata,
  CalculatorMetadata,
  Box1Metadata,
  ChevronRightMetadata,
  ChevronUpMetadata,
  CircleDivideMetadata,
  CircleEqualMetadata,
  CircleMinusMetadata,
  CirclePercentMetadata,
  CirclePlus1Metadata,
  CircleSlashMetadata,
  CircleSlash1Metadata,
  CircleXMetadata,
  ConeMetadata,
  CopyMinusMetadata,
  CopyPlusMetadata,
  CopySlashMetadata,
  CopyXMetadata,
  CuboidMetadata,
  CylinderMetadata,
  DecimalsArrowLeftMetadata,
  DecimalsArrowRightMetadata,
  DecimalsArrowLeft1Metadata,
  DecimalsArrowRight1Metadata,
  DiameterMetadata,
  DiamondPercentMetadata,
  DivideMetadata,
  DraftingCompassMetadata,
  EqualMetadata,
  EqualApproximatelyMetadata,
  EqualNotMetadata,
  Grid2x2Metadata,
  Grid2x2CheckMetadata,
  Grid2x2PlusMetadata, 
  Grid2x2XMetadata,
  Grid3x2Metadata,
  LandPlotMetadata,
  MinusMetadata,
  OctagonXMetadata,
  OmegaMetadata,
  ParenthesesMetadata,
  PercentMetadata,
  PiMetadata,
  PlusMetadata,
  PyramidMetadata,
  RadicalMetadata,
  RadiusMetadata,
  SigmaMetadata,
  SlashMetadata,
  SquareAsteriskMetadata,
  SquareChevronUpMetadata,
  SquareDivideMetadata,
  SquareEqualMetadata,
  SquareFunctionMetadata,
  SquareMinusMetadata,
  SquarePercentMetadata,
  SquarePiMetadata,
  SquarePlusMetadata,
  SquareRadicalMetadata,
  SquareSigmaMetadata,
  SquareSlashMetadata,
  SquareXMetadata,
  Tally1Metadata,
  Tally2Metadata,
  Tally3Metadata,
  Tally5Metadata,
  Tally4Metadata,
  TangentMetadata,
  TriangleRightMetadata,
  VariableMetadata,
  WeightMetadata,
  XMetadata,
  HandMetadata,
  InfoMetadata,
  LifeBuoyMetadata,
  MoonStarMetadata,
  MoonMetadata,
  PersonStandingMetadata,
  ScanEyeMetadata, 
  ScanSearchMetadata,
  SpeechMetadata,
  SunDimMetadata,
  SunMediumMetadata,
  SunMoonMetadata,
  SunMetadata,
  ZoomInMetadata,
  ZoomOutMetadata,
  TransgenderMetadata,
  ActivityMetadata,
  AtSignMetadata,
  AwardMetadata,
  BadgeAlertMetadata,
  BadgeInfoMetadata,
  BanMetadata,
  BellMetadata,
  BellDotMetadata,
  BookUserMetadata,
  BookmarkMetadata,
  BookmarkCheckMetadata,
  BookmarkMinusMetadata,
  BookmarkPlusMetadata,
  BookmarkXMetadata,
  CakeMetadata,
  CircleUserMetadata,
  CircleUserRoundMetadata,
  CogMetadata,
  ContactMetadata,
  ContactRoundMetadata,
  CookieMetadata,
  CreditCardMetadata,
  FileUserMetadata,
  FingerprintMetadata,
  FlagMetadata,
  FlagOffMetadata,
  FrownMetadata,
  BadgeInfo1Metadata,
  GiftMetadata,
  HandCoinsMetadata,
  HandshakeMetadata,
  HeartHandshakeMetadata,
  HeartMinusMetadata,
  HeartPlusMetadata,
  IdCardMetadata,
  IdCardLanyardMetadata,
  InboxMetadata,
  KeyMetadata,
  KeyRoundMetadata,
  KeySquareMetadata,
  LinkMetadata,
  Link1Metadata,
  LocationEditMetadata,
  LogInMetadata,
  LogOutMetadata,
  MailMetadata,
  MapPinMetadata,
  MapPinCheckMetadata,
  MapPinCheckInsideMetadata,
  MapPinHouseMetadata,
  MapPinMinusMetadata,
  MapPinMinusInsideMetadata,
  MapPinPlusMetadata,
  MapPinPlusInsideMetadata,
  MapPinXMetadata,
  MapPinXInsideMetadata,
  MapPinnedMetadata,
  MenuMetadata,
  MessageCircleXMetadata,
  NotebookTabsMetadata,
  PinMetadata,
  RotateCcwKeyMetadata,
  ScanQrCodeMetadata,
  ScanFaceMetadata,
  SettingsMetadata,
  Settings1Metadata,
  ShareMetadata,
  Share1Metadata,
  ShieldMetadata,
  ShieldAlertMetadata,
  ShieldBanMetadata,
  ShieldCheckMetadata,
  ShieldHalfMetadata,
  ShieldMinusMetadata,
  ShieldOffMetadata,
  ShieldPlusMetadata,
  ShieldQuestionMarkMetadata,
  ShieldUserMetadata,
  ShieldXMetadata,
  SlidersHorizontalMetadata,
  SlidersVerticalMetadata,
  SquareUserMetadata,
  SquareUserRoundMetadata,
  StarMetadata,
  TagMetadata,
  TagsMetadata,
  ThumbsDownMetadata,
  ThumbsUpMetadata,
  TicketMetadata,
  TicketsMetadata,
  ToggleLeftMetadata,
  ToggleRightMetadata,
  UserMetadata,
  UserCheckMetadata,
  UserCogMetadata,
  UserLockMetadata,
  UserMinusMetadata,
  UserPenMetadata,
  UserPlusMetadata,
  UserRoundMetadata,
  UserRoundCheckMetadata,
  UserRoundCogMetadata,
  UserRoundMinusMetadata,
  UserRoundPenMetadata,
  UserRoundPlusMetadata,
  UserRoundSearchMetadata,
  UserRoundXMetadata,
  UserSearchMetadata,
  UserXMetadata,
  UsersMetadata,
  UsersRoundMetadata,
  VenetianMaskMetadata,
  VibrateMetadata,
  VibrateOffMetadata,
  WalletMetadata,
  WalletCardsMetadata,
  WalletMinimalMetadata,
  WallpaperMetadata,
  WaypointsMetadata,
  WebhookMetadata,
  WebhookOffMetadata,
  WrenchMetadata, 
} from "./icons"; 
 
export const iconDatabase: Record<string, IconMetadata> = { 

  // Arrows

  "ArrowBigDown": ArrowBigDownMetadata,
  "ArrowBigDownDash": ArrowBigDownDashMetadata,
  "ArrowBigLeft": ArrowBigLeftMetadata,
  "ArrowBigLeftDash": ArrowBigLeftDashMetadata,
  "ArrowBigRight": ArrowBigRightMetadata,
  "ArrowBigRightDash": ArrowBigRightDashMetadata,
  "ArrowBigUp": ArrowBigUpMetadata,
  "ArrowBigUpDash": ArrowBigUpDashMetadata,
  "ArrowDown": ArrowDownMetadata,
  "ArrowDown01": ArrowDown01Metadata,
  "ArrowDown10": ArrowDown10Metadata,
  "ArrowDownAZ": ArrowDownAZMetadata,

  // Design

  "AArrowDown": AArrowDownMetadata,
  "AArrowUp": AArrowUpMetadata,
  "ALargeSmall": ALargeSmallMetadata,
  "AppWindow": AppWindowMetadata,
  "AppWindowMac": AppWindowMacMetadata,
  "Axis3d": Axis3dMetadata,
  "BetweenHorizontalEnd": BetweenHorizontalEndMetadata,
  "BetweenHorizontalStart":BetweenHorizontalStartMetadata,
  "BetweenVerticalEnd": BetweenVerticalEndMetadata,
  "BetweenVerticalStart": BetweenVerticalStartMetadata,
  "Blend": BlendMetadata,
  "BookType": BookTypeMetadata,

  //Buildings
  
  "Anvil": AnvilMetadata,
  "BrickWall": BrickWallMetadata,
  "Building": BuildingMetadata,
  "Building01": Building01Metadata,
  "Castle": CastleMetadata,
  "Church": ChurchMetadata,
  "Dam": DamMetadata,
  "Factory": FactoryMetadata,
  "Fence": FenceMetadata,
  "Hospital": HospitalMetadata,
  "Hotel": HotelMetadata,
  "House": HouseMetadata,

  // Layout

  "AlignCenterHorizontal": AlignCenterHorizontalMetadata,
  "AlignCenterVertical": AlignCenterVerticalMetadata,
  "AlignEndHorizontal": AlignEndHorizontalMetadata,
  "AlignEndVertical": AlignEndVerticalMetadata,
  "AlignHorizontalDistributeCenter": AlignHorizontalDistributeCenterMetadata,
  "AlignHorizontalDistributeEnd": AlignHorizontalDistributeEndMetadata,
  "AlignHorizontalDistributeStart": AlignHorizontalDistributeStartMetadata,
  "AlignHorizontalJustifyCenter": AlignHorizontalJustifyCenterMetadata,
  "AlignHorizontalJustifyEnd": AlignHorizontalJustifyEndMetadata,
  "AlignHorizontalJustifyStart": AlignHorizontalJustifyStartMetadata,
  "AlignHorizontalSpaceAround": AlignHorizontalSpaceAroundMetadata,
  "AlignHorizontalSpaceBetween": AlignHorizontalSpaceBetweenMetadata,

  // Shapes

  "Badge": BadgeMetadata,
  "Blocks": BlocksMetadata,
  "Box": BoxMetadata,
  "Boxes": BoxesMetadata,
  "Circle": CircleMetadata,
  "CircleDashed": CircleDashedMetadata,
  "CircleDot": CircleDotMetadata,
  "CircleDotDashed": CircleDotDashedMetadata,
  "CircleOff": CircleOffMetadata,
  "CircleSlash2": CircleSlash2Metadata,
  "CircleSmall": CircleSmallMetadata,
  "Club": ClubMetadata,

  // Cursors

  "CirclePlus": CirclePlusMetadata,
  "Grab": GrabMetadata,
  "Lasso": LassoMetadata,
  "LassoSelect": LassoSelectMetadata,
  "Loader": LoaderMetadata,
  "LoaderCircle": LoaderCircleMetadata,
  "LoaderPinwheel": LoaderPinwheelMetadata,
  "MousePointer": MousePointerMetadata,
  "MousePointer1": MousePointer1Metadata,
  "MousePointerBan": MousePointerBanMetadata,
  "MousePointerClick": MousePointerClickMetadata,
  "Move": MoveMetadata,

  // Accessibility

  "Accessibility": AccessibilityMetadata,
  "Baby": BabyMetadata,
  "BadgeHelp": BadgeHelpMetadata,
  "CircleHelp": CircleHelpMetadata,
  "Contrast": ContrastMetadata,
  "EarOff": EarOffMetadata,
  "Ear": EarMetadata,
  "Eclipse": EclipseMetadata,
  "EyeClosed": EyeClosedMetadata,
  "EyeOff": EyeOffMetadata,
  "Eye": EyeMetadata,
  "Glasses": GlassesMetadata,
  "Hand": HandMetadata,
  "Info": InfoMetadata,
  "LifeBuoy": LifeBuoyMetadata,
  "MoonM": MoonMetadata,
  "MoonStar": MoonStarMetadata,
  "PersonStanding": PersonStandingMetadata,
  "ScanEye": ScanEyeMetadata,
  "ScanSearch": ScanSearchMetadata,
  "Speech": SpeechMetadata,
  "SunDim": SunDimMetadata,
  "SunMedium": SunMediumMetadata,
  'SunMoon': SunMoonMetadata,
  "Sun": SunMetadata,
  "ZoomIn": ZoomInMetadata,
  "ZoomOut": ZoomOutMetadata,
  "Transgender": TransgenderMetadata,

  // Accounts

  "Activity": ActivityMetadata,
  "AtSign": AtSignMetadata,
  "AwardMetadata": AwardMetadata,
  "BadgeAlert": BadgeAlertMetadata,
  "BadgeInfo1": BadgeInfo1Metadata,
  "Ban": BanMetadata,
  "Bell": BellMetadata,
  "BellDot": BellDotMetadata,
  "BookUser": BookUserMetadata,
  "Bookmark": BookmarkMetadata,
  "BookmarkCheck": BookmarkCheckMetadata,
  "BookmarkMinus": BookmarkMinusMetadata,
  "BookmarkPlus": BookmarkPlusMetadata,
  "BookmarkX": BookmarkXMetadata,
  "Cake": CakeMetadata,
  "CircleUser": CircleUserMetadata,
  "CircleUserRound": CircleUserRoundMetadata,
  "Cog": CogMetadata,
  "Contact": ContactMetadata,
  "ContactRound": ContactRoundMetadata,
  "Cookie": CookieMetadata,
  "CreditCard": CreditCardMetadata,
  "FileUser": FileUserMetadata,
  "Fingerprint": FingerprintMetadata,
  "Flag": FlagMetadata,
  "FlagOff": FlagOffMetadata,
  "Frown": FrownMetadata,
  "Gift": GiftMetadata,
  "HandCoins": HandCoinsMetadata,
  "Handshake": HandshakeMetadata,
  "HeartHandshake": HeartHandshakeMetadata,
  "HeartMinus": HeartMinusMetadata,
  "HeartPlus": HeartPlusMetadata,
  "IdCard": IdCardMetadata,
  "IdCardLanyard":IdCardLanyardMetadata,
  "Inbox": InboxMetadata,
  "Key": KeyMetadata,
  "KeyRound": KeyRoundMetadata,
  "KeySquare": KeySquareMetadata,
  "Link": LinkMetadata,
  "Link1": Link1Metadata,
  "LocationEdit": LocationEditMetadata,
  "LogIn": LogInMetadata,
  "LogOut": LogOutMetadata,
  "Mail": MailMetadata,
  "MapPin": MapPinMetadata,
  "MapPinCheck": MapPinCheckMetadata,
  "MapPinCheckInside": MapPinCheckInsideMetadata,
  "MapPinHouse": MapPinHouseMetadata,
  "MapPinMinus": MapPinMinusMetadata,
  "MapPinMinusInside": MapPinMinusInsideMetadata,
  "MapPinPlus": MapPinPlusMetadata,
  "MapPinPlusInside": MapPinPlusInsideMetadata,
  "MapPinX": MapPinXMetadata,
  "MapPinXInside": MapPinXInsideMetadata,
  "MapPinned": MapPinnedMetadata,
  "Menu": MenuMetadata,
  "MessageCircleX": MessageCircleXMetadata,
  "NotebookTabs": NotebookTabsMetadata,
  "Pin": PinMetadata,
  "RotateCcwKey": RotateCcwKeyMetadata,
  "ScanFace": ScanFaceMetadata,
  "ScanQrCode": ScanQrCodeMetadata,
  "Settings": SettingsMetadata,
  "Settings1": Settings1Metadata,
  "Share": ShareMetadata,
  "Share1": Share1Metadata,
  "Shield": ShieldMetadata,
  "ShieldAlert": ShieldAlertMetadata,
  "ShieldBan": ShieldBanMetadata,
  "ShieldCheck": ShieldCheckMetadata,
  "ShieldHalf": ShieldHalfMetadata,
  "ShieldMinus": ShieldMinusMetadata,
  "ShieldOff": ShieldOffMetadata,
  "ShieldPlus": ShieldPlusMetadata,
  "ShieldQuestionMark": ShieldQuestionMarkMetadata,
  "ShieldUser": ShieldUserMetadata,
  "ShieldX": ShieldXMetadata,
  "SlidersHorizontal": SlidersHorizontalMetadata,
  "SlidersVertical": SlidersVerticalMetadata,
  "SquareUser": SquareUserMetadata,
  "SquareUserRound": SquareUserRoundMetadata,
  "Star": StarMetadata,
  "Tag": TagMetadata,
  "Tags": TagsMetadata,
  "ThumbsDown": ThumbsDownMetadata,
  "ThumbsUp": ThumbsUpMetadata,
  "Ticket": TicketMetadata,
  "Tickets": TicketsMetadata,
  "ToggleLeft": ToggleLeftMetadata,
  "ToggleRight": ToggleRightMetadata,
  "User": UserMetadata,
  "UserCheck": UserCheckMetadata,
  "UserCog": UserCogMetadata,
  "UserLock": UserLockMetadata,
  "UserMinus": UserMinusMetadata,
  "UserPen": UserPenMetadata,
  "UserPlus": UserPlusMetadata,
  "UserRound": UserRoundMetadata,
  "UserRoundCheck": UserRoundCheckMetadata,
  "UserRoundCog": UserRoundCogMetadata,
  "UserRoundMinus": UserRoundMinusMetadata,
  "UserRoundPen": UserRoundPenMetadata,
  "UserRoundPlus": UserRoundPlusMetadata,
  "UserRoundSearch": UserRoundSearchMetadata,
  "UserRoundX": UserRoundXMetadata,
  "UserSearch": UserSearchMetadata,
  "UserX": UserXMetadata,
  "Users": UsersMetadata,
  "UsersRound": UsersRoundMetadata,
  "VenetianMask": VenetianMaskMetadata,
  "Vibrate": VibrateMetadata,
  "VibrateOff": VibrateOffMetadata,
  "Wallet": WalletMetadata,
  "WalletCards": WalletCardsMetadata,
  "WalletMinimal": WalletMinimalMetadata,
  "Wallpaper": WallpaperMetadata,
  "Waypoints": WaypointsMetadata,
  "Webhook": WebhookMetadata,
  "WebhookOff": WebhookOffMetadata,
  "Wrench": WrenchMetadata,

  // Mathematics

  "Asterisk": AsteriskMetadata,
  "BadgePercent": BadgePercentMetadata,
  "Calculator": CalculatorMetadata,
  "Box1": Box1Metadata,
  "ChevronRight": ChevronRightMetadata,
  "ChevronUp": ChevronUpMetadata,
  "CircleDivide": CircleDivideMetadata,
  "CircleEqual": CircleEqualMetadata,
  "CircleMinus": CircleMinusMetadata,
  "CirclePercent": CirclePercentMetadata,
  "CirclePlus1": CirclePlus1Metadata,
  "CircleSlash": CircleSlashMetadata,
  "CircleSlash1": CircleSlash1Metadata,
  "CircleX": CircleXMetadata,
  "Cone": ConeMetadata,
  "CopyMinus": CopyMinusMetadata,
  "CopyPlus": CopyPlusMetadata,
  "CopySlash": CopySlashMetadata,
  "CopyX": CopyXMetadata,
  "Cuboid": CuboidMetadata,
  "Cylinder": CylinderMetadata,
  "DecimalsArrowLeft": DecimalsArrowLeftMetadata,
  "DecimalsArrowLeft1": DecimalsArrowLeft1Metadata,
  "DecimalsArrowRight": DecimalsArrowRightMetadata,
  "DecimalsArrowRight1": DecimalsArrowRight1Metadata,
  "Diameter": DiameterMetadata,
  "DiamondPercent": DiamondPercentMetadata,
  "Divide": DivideMetadata,
  "DraftingCompass": DraftingCompassMetadata,
  "Equal": EqualMetadata,
  "EqualApproximately": EqualApproximatelyMetadata,
  "EqualNot": EqualNotMetadata,
  "Grid2x2": Grid2x2Metadata,
  "Grid2x2Check": Grid2x2CheckMetadata,
  "Grid2x2Plus": Grid2x2PlusMetadata,
  "Grid2x2X": Grid2x2XMetadata,
  "Grid3x2": Grid3x2Metadata,
  "LandPlot": LandPlotMetadata,
  "Minus": MinusMetadata,
  "OctagonX": OctagonXMetadata,
  "Omega": OmegaMetadata,
  "Parentheses": ParenthesesMetadata,
  "Percent": PercentMetadata,
  "Pi": PiMetadata,
  "Plus": PlusMetadata,
  "Pyramid": PyramidMetadata,
  "Radical": RadicalMetadata,
  "Radius": RadiusMetadata,
  "Sigma": SigmaMetadata,
  "Slash": SlashMetadata,
  "SquareAsterisk": SquareAsteriskMetadata,
  "SquareChevronUp": SquareChevronUpMetadata,
  "SquareDivide": SquareDivideMetadata,
  "SquareEqual": SquareEqualMetadata,
  "SquareFunction": SquareFunctionMetadata,
  "SquareMinus": SquareMinusMetadata,
  "SquarePercent": SquarePercentMetadata,
  "SquarePi": SquarePiMetadata,
  "SquarePlus": SquarePlusMetadata,
  "SquareRadical": SquareRadicalMetadata,
  "SquareSigma": SquareSigmaMetadata,
  "SquareSlash": SquareSlashMetadata,
  "SquareX": SquareXMetadata,
  "Tally1": Tally1Metadata,
  "Tally2": Tally2Metadata,
  "Tally3": Tally3Metadata,
  "Tally4": Tally4Metadata,
  "Tally5": Tally5Metadata,
  "Tangent": TangentMetadata,
  "TriangleRight": TriangleRightMetadata,
  "Variable": VariableMetadata,
  "Weight": WeightMetadata,
  "X": XMetadata,

};

// Get all icons
export function getAllIcons(): IconMetadata[] {
  return Object.values(iconDatabase);
}

 
// Get icon by name
export function getIconByName(name: string): IconMetadata | undefined {
  return iconDatabase[name];
}
 

// Get icons by category
export function getIconsByCategory(category: string): IconMetadata[] {
  return Object.values(iconDatabase).filter(icon => icon.category === category);
}

// Get icons by tag
export function getIconsByTag(tag: string): IconMetadata[] {
  return Object.values(iconDatabase).filter(icon => 
    icon.tags.some(t => t.toLowerCase().includes(tag.toLowerCase()))
  );
}

// Get all categories
export function getAllCategories(): string[] {
  const categories = new Set<string>();
  Object.values(iconDatabase).forEach(icon => {
    categories.add(icon.category);
  });
  return Array.from(categories);
}

// Get all tags
export function getAllTags(): string[] {
  const tags = new Set<string>();
  Object.values(iconDatabase).forEach(icon => {
    icon.tags.forEach(tag => tags.add(tag));
  });
  return Array.from(tags);
}

// Search icons
export function searchIcons(query: string): IconMetadata[] {
  const lowercaseQuery = query.toLowerCase();
  return Object.values(iconDatabase).filter(icon => 
    icon.name.toLowerCase().includes(lowercaseQuery) ||
    icon.category.toLowerCase().includes(lowercaseQuery) ||
    icon.tags.some(tag => tag.toLowerCase().includes(lowercaseQuery)) ||
    (icon.description && icon.description.toLowerCase().includes(lowercaseQuery))
  );
}
